name: Daily Vercel Deploy
on:
  schedule:
    - cron: "15 3 * * *"  # täglich 03:15 UTC = 05:15 Berlin
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: curl -fsS -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
